### ISSUE TITLE
Update svelte and sveltekit creation script

### ISSUE THREAD

**Issue by phoebehala** [sans-ui-org/sans-ui#209]
According to the update from svelte official document, I'd like to change the script on the installation page of SanS-UI document
<img width="979" alt="image" src="https://github.com/user-attachments/assets/a84e90bf-deab-4e66-b9bd-56d1e77530ca">

**Comment by kuri-sun** [comment]
Let's go!

**Comment by phoebehala** [comment]
For svelte installation, the official site recommend using svelte-kit. Should we put the same script on SanS-UI document or remove and leave the wording like:
'According to [the official Svelte documentation](https://svelte.dev/docs/svelte/getting-started), using SvelteKit is recommended.'
<img width="973" alt="image" src="https://github.com/user-attachments/assets/e15201d7-d31f-46e7-af9c-3b06d95e152d">
